import { createReport } from './firebase';

const dummyReports = [
  {
    name: 'Bean',
    species: 'cat',
    color: 'Black',
    size: 'Medium',
    gender: 'Female',
    breed: 'Domestic Shorthair',
    picture: 'https://i.ibb.co/jkSLbB27/cat-1.jpg',
    lostLocation: ['42.605255', '-81.609216'],
    foundLocation: ['42.605255', '-81.609216'],
    status: 'complete',
    email: 'jessica.martin84@email.com',
  },
  {
    name: 'Max',
    species: 'dog',
    color: 'Golden',
    size: 'Large',
    gender: 'Male',
    breed: 'Golden Retriever',
    picture: 'https://i.ibb.co/rKNkY74b/dog-1.jpg',
    lostLocation: ['42.612345', '-81.610123'],
    foundLocation: null,
    status: 'lost',
    email: 'ryan.thompson22@inbox.net',
  },
  {
    name: 'Bella',
    species: 'dog',
    color: 'Brown',
    size: 'Medium',
    gender: 'Female',
    breed: 'Unknown',
    picture: 'https://i.ibb.co/Y7MxtjCh/dog-2.jpg',
    lostLocation: null,
    foundLocation: ['42.598765', '-81.615432'],
    status: 'found',
    email: 'sophia.garcia77@mailhub.org',
  },
  {
    name: 'Luna',
    species: 'cat',
    color: 'Gray',
    size: 'Small',
    gender: 'Female',
    breed: 'Siamese',
    picture: 'https://i.ibb.co/7J6Z6qTK/cat-2.jpg',
    lostLocation: ['42.60789', '-81.62'],
    foundLocation: null,
    status: 'lost',
    email: 'daniel.rodriguez04@fastmail.net',
  },
  {
    name: 'Charlie',
    species: 'dog',
    color: 'Black',
    size: 'Medium',
    gender: 'Male',
    breed: 'Beagle',
    picture: 'https://i.ibb.co/kg7b5K1q/dog-3.jpg',
    lostLocation: ['42.6', '-81.605'],
    foundLocation: ['42.6', '-81.605'],
    status: 'complete',
    email: 'emma.wilson98@myemail.co',
  },
  {
    name: 'Simba',
    species: 'cat',
    color: 'Orange',
    size: 'Large',
    gender: 'Male',
    breed: 'Unknown',
    picture: 'https://i.ibb.co/7J5XBMgd/cat-3.jpg',
    lostLocation: null,
    foundLocation: ['42.611111', '-81.606666'],
    status: 'found',
    email: 'michael.brown56@webmail.com',
  },
  {
    name: 'Rocky',
    species: 'dog',
    color: 'Brown',
    size: 'Extra Large',
    gender: 'Male',
    breed: 'German Shepherd',
    picture: 'https://i.ibb.co/WNCZVgBc/dog-4.jpg',
    lostLocation: ['42.62', '-81.6'],
    foundLocation: null,
    status: 'lost',
    email: 'olivia.taylor31@postbox.net',
  },
  {
    name: 'Chloe',
    species: 'cat',
    color: 'Gray',
    size: 'Small',
    gender: 'Female',
    breed: 'Persian',
    picture: 'https://i.ibb.co/Nd2W8K6F/cat-4.jpg',
    lostLocation: ['42.603', '-81.608'],
    foundLocation: ['42.603', '-81.608'],
    status: 'complete',
    email: 'jason.anderson99@outlook.me',
  },
  {
    name: 'Daisy',
    species: 'dog',
    color: 'Black',
    size: 'Medium',
    gender: 'Female',
    breed: 'Border Collie',
    picture: 'https://i.ibb.co/mrpJPXpf/dog-5.jpg',
    lostLocation: ['42.615', '-81.612'],
    foundLocation: null,
    status: 'lost',
    email: 'lisa.white12@mailconnect.org',
  },
  {
    name: 'Milo',
    species: 'cat',
    color: 'White',
    size: 'Small',
    gender: 'Male',
    breed: 'Unknown',
    picture: 'https://i.ibb.co/ymdxxq7X/cat-5.jpg',
    lostLocation: null,
    foundLocation: ['42.609', '-81.614'],
    status: 'found',
    email: 'nathan.harris76@inboxnow.com',
  },
  {
    name: 'Sophie',
    species: 'dog',
    color: 'Beige',
    size: 'Medium',
    gender: 'Female',
    breed: 'Labrador Retriever',
    picture: 'https://i.ibb.co/5X34fmrS/dog-6.jpg',
    lostLocation: ['42.6065', '-81.611'],
    foundLocation: ['42.6065', '-81.611'],
    status: 'found',
    email: 'megan.lee43@netpost.net',
  },
  {
    name: 'Duke',
    species: 'dog',
    color: 'Black',
    size: 'Extra Large',
    gender: 'Male',
    breed: 'Rottweiler',
    picture: 'https://i.ibb.co/HpPn1kFy/dog-7.jpg',
    lostLocation: ['42.622', '-81.607'],
    foundLocation: null,
    status: 'lost',
    email: 'chris.walker88@onlinebox.org',
  },
];

export const addDummy = () =>
  dummyReports.forEach(async (report) => {
    await createReport(report);
  });
