export const dummyReports = [
  {
    id: 1,
    name: 'Bean',
    description: 'A timid black cat with a small white spot under her chin.',
    specie: 'cat',
    color: 'Black',
    size: 'Medium',
    gender: 'Female',
    breed: 'Domestic Shorthair',
    picture: 'https://i.ibb.co/jkSLbB27/cat-1.jpg',
    lostLocation: ['42.605255, -81.609216'],
    foundLocation: ['42.605255, -81.609216'],
    status: 'complete',
  },
  {
    id: 2,
    name: 'Max',
    description:
      'An energetic golden retriever that loves to play fetch in the park.',
    specie: 'dog',
    color: 'Golden',
    size: 'Large',
    gender: 'Male',
    breed: 'Golden Retriever',
    picture: 'https://i.ibb.co/rKNkY74b/dog-1.jpg',
    lostLocation: ['42.612345, -81.610123'],
    foundLocation: null,
    status: 'lost',
  },
  {
    id: 3,
    name: 'Bella',
    description:
      'A gentle dog with a mix of brown and black fur, found wandering near a busy street. Breed unknown.',
    specie: 'dog',
    color: 'Brown',
    size: 'Medium',
    gender: 'Female',
    breed: 'Unknown',
    picture: 'https://i.ibb.co/Y7MxtjCh/dog-2.jpg',
    lostLocation: null,
    foundLocation: ['42.598765, -81.615432'],
    status: 'found',
  },
  {
    id: 4,
    name: 'Luna',
    description:
      'A curious gray and white cat often seen near the neighborhood park.',
    specie: 'cat',
    color: 'Gray',
    size: 'Small',
    gender: 'Female',
    breed: 'Siamese',
    picture: 'https://i.ibb.co/7J6Z6qTK/cat-2.jpg',
    lostLocation: ['42.60789, -81.62'],
    foundLocation: null,
    status: 'lost',
  },
  {
    id: 5,
    name: 'Charlie',
    description:
      'A playful dog spotted near the downtown area with a striking black and brown coat.',
    specie: 'dog',
    color: 'Black',
    size: 'Medium',
    gender: 'Male',
    breed: 'Beagle',
    picture: 'https://i.ibb.co/kg7b5K1q/dog-3.jpg',
    lostLocation: ['42.6, -81.605'],
    foundLocation: ['42.6, -81.605'],
    status: 'complete',
  },
  {
    id: 6,
    name: 'Simba',
    description:
      'A regal-looking cat with a striking orange and white coat, found near a local market. Breed unknown.',
    specie: 'cat',
    color: 'Orange',
    size: 'Large',
    gender: 'Male',
    breed: 'Unknown',
    picture: 'https://i.ibb.co/7J5XBMgd/cat-3.jpg',
    lostLocation: null,
    foundLocation: ['42.611111, -81.606666'],
    status: 'found',
  },
  {
    id: 7,
    name: 'Rocky',
    description:
      'A strong and brave dog with a rugged appearance, last seen near the river.',
    specie: 'dog',
    color: 'Brown',
    size: 'Extra Large',
    gender: 'Male',
    breed: 'German Shepherd',
    picture: 'https://i.ibb.co/WNCZVgBc/dog-4.jpg',
    lostLocation: ['42.62, -81.6'],
    foundLocation: null,
    status: 'lost',
  },
  {
    id: 8,
    name: 'Chloe',
    description:
      'A sweet cat with a distinctive gray and beige coat, known for her affectionate nature.',
    specie: 'cat',
    color: 'Gray',
    size: 'Small',
    gender: 'Female',
    breed: 'Persian',
    picture: 'https://i.ibb.co/Nd2W8K6F/cat-4.jpg',
    lostLocation: ['42.603, -81.608'],
    foundLocation: ['42.603, -81.608'],
    status: 'complete',
  },
  {
    id: 9,
    name: 'Daisy',
    description:
      'A friendly dog with a mix of black and brown patches, last seen near the suburban park.',
    specie: 'dog',
    color: 'Black',
    size: 'Medium',
    gender: 'Female',
    breed: 'Border Collie',
    picture: 'https://i.ibb.co/mrpJPXpf/dog-5.jpg',
    lostLocation: ['42.615, -81.612'],
    foundLocation: null,
    status: 'lost',
  },
  {
    id: 10,
    name: 'Milo',
    description:
      'A playful cat found near the local grocery store. Breed unknown.',
    specie: 'cat',
    color: 'White',
    size: 'Small',
    gender: 'Male',
    breed: 'Unknown',
    picture: 'https://i.ibb.co/ymdxxq7X/cat-5.jpg',
    lostLocation: null,
    foundLocation: ['42.609, -81.614'],
    status: 'found',
  },
  {
    id: 11,
    name: 'Sophie',
    description:
      'A calm and well-behaved dog, known for her gentle eyes and friendly demeanor.',
    specie: 'dog',
    color: 'Beige',
    size: 'Medium',
    gender: 'Female',
    breed: 'Labrador Retriever',
    picture: 'https://i.ibb.co/5X34fmrS/dog-6.jpg',
    lostLocation: ['42.6065, -81.611'],
    foundLocation: ['42.6065, -81.611'],
    status: 'found',
  },
  {
    id: 12,
    name: 'Duke',
    description:
      'A robust dog with a muscular build, last seen roaming near the industrial area.',
    specie: 'dog',
    color: 'Black',
    size: 'Extra Large',
    gender: 'Male',
    breed: 'Rottweiler',
    picture: 'https://i.ibb.co/HpPn1kFy/dog-7.jpg',
    lostLocation: ['42.622, -81.607'],
    foundLocation: null,
    status: 'lost',
  },
];
